# Generated by Django 3.2.7 on 2021-10-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rate_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_from', models.EmailField(max_length=30)),
                ('subject', models.CharField(max_length=25)),
                ('message', models.TextField()),
            ],
        ),
    ]
