# Generated by Django 3.2.7 on 2021-10-13 14:22

from django.db import migrations


def forwards(apps, schema_editor):
    Rate = apps.get_model('currency', 'Rate')
    for rate in Rate.objects.all():
        rate.type_new = 1 if 'eur' in rate.type else 0
        rate.save()


def backwards(apps, schema_editor):
    #Post = apps.get_model('blog', 'Post')
    print('HELLO FROM BACKWARDS!')



class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_auto_20211011_0938'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
