# Generated by Django 3.2.7 on 2021-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_rate_type_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='type_new',
            field=models.PositiveSmallIntegerField(choices=[('0', 'Dollar'), ('1', 'Euro')], default=100),
        ),
    ]
