# Generated by Django 3.2.7 on 2021-10-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_rate_type_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='type',
        ),
    ]
