# Generated by Django 3.2.7 on 2021-10-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_remove_rate_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='type_new',
            new_name='type',
        ),
    ]
