# Generated by Django 3.2.7 on 2021-10-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_rename_type_new_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Dollar'), (1, 'Euro')]),
        ),
    ]
