# Generated by Django 3.2.7 on 2021-10-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_alter_rate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('counter', models.PositiveBigIntegerField()),
                ('request_method', models.PositiveSmallIntegerField(choices=[(0, 'Get'), (1, 'Post')])),
            ],
        ),
    ]
